/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.ventanas.vistas;

import javax.swing.ImageIcon;
import javax.swing.JPanel;
import org.example.ventanas.vistas.panelesTabbledVistas.PanelCargaUsuario;
import org.example.ventanas.vistas.panelesTabbledVistas.PanelEdicionUsuario;
import org.example.ventanas.vistas.panelesTabbledVistas.PanelTablaUsuarios;
import org.example.ventanas.vistas.panelesTabbledVistas.UtilidadesPaneles;

/**
 *
 * @author Agus-Notebook
 */
public class VistaUsuarios extends javax.swing.JPanel implements UtilidadesPaneles{

    /**
     * Creates new form VistaUsuarios
     */
    public VistaUsuarios() {
        initComponents();
        iniciarPanales();
    }
    
    private ImageIcon crearIcono(String pathName){
        return new ImageIcon(pathName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundVentanaUsuario = new javax.swing.JPanel();
        contenedorPanelVistaUsuario = new javax.swing.JTabbedPane();

        setMaximumSize(new java.awt.Dimension(800, 560));
        setMinimumSize(new java.awt.Dimension(800, 560));

        backgroundVentanaUsuario.setBackground(new java.awt.Color(121, 215, 220));
        backgroundVentanaUsuario.setMaximumSize(new java.awt.Dimension(800, 560));
        backgroundVentanaUsuario.setMinimumSize(new java.awt.Dimension(800, 560));

        contenedorPanelVistaUsuario.setBackground(new java.awt.Color(142, 233, 239));
        contenedorPanelVistaUsuario.setForeground(new java.awt.Color(57, 136, 158));
        contenedorPanelVistaUsuario.setToolTipText("");
        contenedorPanelVistaUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        contenedorPanelVistaUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contenedorPanelVistaUsuario.setMaximumSize(new java.awt.Dimension(800, 510));
        contenedorPanelVistaUsuario.setMinimumSize(new java.awt.Dimension(800, 510));
        contenedorPanelVistaUsuario.setPreferredSize(new java.awt.Dimension(800, 510));

        javax.swing.GroupLayout backgroundVentanaUsuarioLayout = new javax.swing.GroupLayout(backgroundVentanaUsuario);
        backgroundVentanaUsuario.setLayout(backgroundVentanaUsuarioLayout);
        backgroundVentanaUsuarioLayout.setHorizontalGroup(
            backgroundVentanaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorPanelVistaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        backgroundVentanaUsuarioLayout.setVerticalGroup(
            backgroundVentanaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorPanelVistaUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundVentanaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundVentanaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundVentanaUsuario;
    private javax.swing.JTabbedPane contenedorPanelVistaUsuario;
    // End of variables declaration//GEN-END:variables

    @Override
    public void iniciarPanales() {
        PanelCargaUsuario panel1 = new PanelCargaUsuario();
        PanelTablaUsuarios panel2 = new PanelTablaUsuarios();
        PanelEdicionUsuario panel3 = new PanelEdicionUsuario();
        contenedorPanelVistaUsuario.addTab("Carga Usuario", panel1);
        contenedorPanelVistaUsuario.addTab("Ver Usuario", panel2);
        contenedorPanelVistaUsuario.addTab("Editar Usuario", panel3);
        iconosSolapas();
        
        contenedorPanelVistaUsuario.setSelectedIndex(0);
    }
    
    @Override
    public void iconosSolapas(){
        contenedorPanelVistaUsuario.setIconAt(0, crearIcono("icons\\iconsSolapasPaneles\\agregar-usuario.png"));
        contenedorPanelVistaUsuario.setIconAt(1, crearIcono("icons\\iconsSolapasPaneles\\lupa.png"));
        contenedorPanelVistaUsuario.setIconAt(2, crearIcono("icons\\iconsSolapasPaneles\\editar.png"));
    }
}
