/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.ventanas.vistas;

import javax.swing.ImageIcon;
import org.example.ventanas.vistas.panelesTabbledVistas.PanelCargaProducto;
import org.example.ventanas.vistas.panelesTabbledVistas.PanelTablaProductos;
import org.example.ventanas.vistas.panelesTabbledVistas.UtilidadesPaneles;

/**
 *
 * @author Agus-Notebook
 */
public class VistaProductos extends javax.swing.JPanel implements UtilidadesPaneles{

    /**
     * Creates new form VistaProductos
     */
    public VistaProductos() {
        initComponents();
        iniciarPanales();
    }
    private ImageIcon crearIcono(String pathName){
        return new ImageIcon(pathName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundVistaProducto = new javax.swing.JPanel();
        contenedorPanelVistaProducto = new javax.swing.JTabbedPane();

        setMaximumSize(new java.awt.Dimension(800, 560));
        setMinimumSize(new java.awt.Dimension(800, 560));

        backgroundVistaProducto.setBackground(new java.awt.Color(121, 215, 220));
        backgroundVistaProducto.setMaximumSize(new java.awt.Dimension(800, 560));
        backgroundVistaProducto.setMinimumSize(new java.awt.Dimension(800, 560));
        backgroundVistaProducto.setPreferredSize(new java.awt.Dimension(800, 560));

        contenedorPanelVistaProducto.setBackground(new java.awt.Color(142, 233, 239));
        contenedorPanelVistaProducto.setForeground(new java.awt.Color(57, 136, 158));
        contenedorPanelVistaProducto.setToolTipText("");
        contenedorPanelVistaProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        contenedorPanelVistaProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contenedorPanelVistaProducto.setMaximumSize(new java.awt.Dimension(800, 510));
        contenedorPanelVistaProducto.setMinimumSize(new java.awt.Dimension(800, 510));
        contenedorPanelVistaProducto.setPreferredSize(new java.awt.Dimension(800, 510));

        javax.swing.GroupLayout backgroundVistaProductoLayout = new javax.swing.GroupLayout(backgroundVistaProducto);
        backgroundVistaProducto.setLayout(backgroundVistaProductoLayout);
        backgroundVistaProductoLayout.setHorizontalGroup(
            backgroundVistaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundVistaProductoLayout.createSequentialGroup()
                .addComponent(contenedorPanelVistaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        backgroundVistaProductoLayout.setVerticalGroup(
            backgroundVistaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorPanelVistaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundVistaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundVistaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundVistaProducto;
    private javax.swing.JTabbedPane contenedorPanelVistaProducto;
    // End of variables declaration//GEN-END:variables

    @Override
    public void iniciarPanales() {
        PanelCargaProducto panel1 = new PanelCargaProducto();
        PanelTablaProductos panel2 = new PanelTablaProductos();
        contenedorPanelVistaProducto.addTab("Carga Producto", panel1);
        contenedorPanelVistaProducto.addTab("Ver Productos", panel2);
        iconosSolapas();
        contenedorPanelVistaProducto.setSelectedIndex(0);
    }

    @Override
    public void iconosSolapas() {
        contenedorPanelVistaProducto.setIconAt(0, crearIcono("icons\\iconsSolapasPaneles\\agregar-usuario.png"));
        contenedorPanelVistaProducto.setIconAt(1, crearIcono("icons\\iconsSolapasPaneles\\lupa.png"));
        
    }
}
