/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.ventanas.vistas.panelesTabbledVistas;

import com.org.example.clases.Productos;
import com.org.example.Exceptions.ProductoCargaDatosException;
import com.org.example.clases.Pedido;
import com.org.example.clases.Productos;
import com.org.example.service.GestionImpleProducto;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListCellRenderer;

/**
 * @author Agus-Notebook
 */
public class PanelCargaProducto extends javax.swing.JPanel{
    private final GestionImpleProducto gestor = new GestionImpleProducto();
    private Productos dato = new Productos();
    /**
     * Creates new form PanelCargaProducto
     */
    public PanelCargaProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanelCargaProducto = new javax.swing.JPanel();
        iconoPanelCarga = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnLimpiarIngreso1 = new javax.swing.JButton();
        btnGuardarIngreso = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ingresoMarca = new javax.swing.JTextField();
        ingresoNombre = new javax.swing.JTextField();
        ingresoElavoracion = new javax.swing.JTextField();
        ingresoVencimiento = new javax.swing.JTextField();
        ingresoPrecio = new javax.swing.JTextField();
        selectorCategoria = new javax.swing.JComboBox<>();
        ingresoStock = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(800, 510));
        setMinimumSize(new java.awt.Dimension(800, 510));
        setPreferredSize(new java.awt.Dimension(800, 510));

        backgroundPanelCargaProducto.setBackground(new java.awt.Color(147, 118, 224));
        backgroundPanelCargaProducto.setMaximumSize(new java.awt.Dimension(800, 560));
        backgroundPanelCargaProducto.setMinimumSize(new java.awt.Dimension(800, 560));
        backgroundPanelCargaProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoPanelCarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lista-de-verificacion (1).png"))); // NOI18N
        backgroundPanelCargaProducto.add(iconoPanelCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 170, 201));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 204, 255)));

        btnLimpiarIngreso1.setBackground(new java.awt.Color(172, 188, 255));
        btnLimpiarIngreso1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiarIngreso1.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarIngreso1.setText("LIMPIAR");
        btnLimpiarIngreso1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpiarIngreso1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimpiarIngreso1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimpiarIngreso1MouseExited(evt);
            }
        });
        btnLimpiarIngreso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarIngreso1ActionPerformed(evt);
            }
        });

        btnGuardarIngreso.setBackground(new java.awt.Color(172, 188, 255));
        btnGuardarIngreso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardarIngreso.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarIngreso.setText("GUARDAR");
        btnGuardarIngreso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardarIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarIngresoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarIngresoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarIngresoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnLimpiarIngreso1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardarIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiarIngreso1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        backgroundPanelCargaProducto.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 350, 90));

        jPanel2.setBackground(new java.awt.Color(232, 147, 207));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(255, 204, 255)));

        ingresoMarca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ingresoMarca.setForeground(new java.awt.Color(153, 153, 153));
        ingresoMarca.setText("   Ingrese Marca del Producto");
        ingresoMarca.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ingresoMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresoMarcaMouseClicked(evt);
            }
        });

        ingresoNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ingresoNombre.setForeground(new java.awt.Color(153, 153, 153));
        ingresoNombre.setText("   Ingrese Nombre del Producto");
        ingresoNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresoNombreMouseClicked(evt);
            }
        });
        ingresoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoNombreActionPerformed(evt);
            }
        });

        ingresoElavoracion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ingresoElavoracion.setForeground(new java.awt.Color(153, 153, 153));
        ingresoElavoracion.setText("   Ingrese Fecha de Elaboracion xx/xx/xxxx");
        ingresoElavoracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresoElavoracionMouseClicked(evt);
            }
        });

        ingresoVencimiento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ingresoVencimiento.setForeground(new java.awt.Color(153, 153, 153));
        ingresoVencimiento.setText("   Ingrese Fecha de Vencimiento xx/xx/xxxx");
        ingresoVencimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresoVencimientoMouseClicked(evt);
            }
        });
        ingresoVencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoVencimientoActionPerformed(evt);
            }
        });

        ingresoPrecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ingresoPrecio.setForeground(new java.awt.Color(153, 153, 153));
        ingresoPrecio.setText("   Ingrese Precio Producto");
        ingresoPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresoPrecioMouseClicked(evt);
            }
        });
        ingresoPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoPrecioActionPerformed(evt);
            }
        });

        selectorCategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectorCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "LIMPIEZA", "COMIDA", "JUGUETERIA", "BEBIDAS", "CONGELADOS", "LACTEOS", "VARIOS" }));
        selectorCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorCategoriaActionPerformed(evt);
            }
        });

        ingresoStock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ingresoStock.setForeground(new java.awt.Color(153, 153, 153));
        ingresoStock.setText("   Ingrese Stock  Producto");
        ingresoStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresoStockMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ingresoElavoracion, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresoVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ingresoStock, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectorCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ingresoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ingresoMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(ingresoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ingresoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ingresoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ingresoVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ingresoElavoracion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ingresoStock, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ingresoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(selectorCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        backgroundPanelCargaProducto.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 480, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanelCargaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanelCargaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    /**
     * Restablece los parametros de los Textos Ingreso
     */
    private void restablecerTextoIngreso() {
        ingresoMarca.setForeground(new Color(153, 153, 153));
        ingresoNombre.setForeground(new Color(153, 153, 153));
        ingresoElavoracion.setForeground(new Color(153, 153, 153));
        ingresoVencimiento.setForeground(new Color(153, 153, 153));
        ingresoStock.setForeground(new Color(153, 153, 153));
        ingresoPrecio.setForeground(new Color(153, 153, 153));
        ingresoMarca.setText("   Ingrese Marca del Producto");
        ingresoNombre.setText("   Ingrese Nombre del Producto");
        ingresoElavoracion.setText("   Ingrese Fecha de Elaboracion xx/xx/xxxx");
        ingresoVencimiento.setText("   Ingrese Fecha de Vencimiento xx/xx/xxxx");
        ingresoStock.setText("   Ingrese Stock Producto");
        ingresoPrecio.setText("   Ingrese Precio Producto");
    }

    /**
     * Funcion que setea un color al txto ingresado
     *
     * @param ingreso
     */
    private void edicionLetraColortexto(JTextField ingreso) {
        ingreso.setText("");
        ingreso.setForeground(Color.BLACK);
    }
    

    /**
     * Funcion que verifica si los datos ingresados son correctos
     * @return boolean true si los datos son correctos
     * @throws ProductoCargaDatosException
     */
    private boolean verificacionFormato() throws ProductoCargaDatosException {
        if (gestor.verificacionIngresosBases(ingresoMarca.getText(),
                ingresoNombre.getText(), ingresoElavoracion.getText(),
                ingresoVencimiento.getText(), ingresoStock.getText(),
                ingresoPrecio.getText())) {
            if (gestor.verificarIngresosVacios(ingresoMarca.getText(),
                    ingresoNombre.getText(), ingresoElavoracion.getText(),
                    ingresoVencimiento.getText(), ingresoStock.getText(),
                    ingresoPrecio.getText())) {
                if (gestor.verificacionFormatoFechas(ingresoElavoracion.getText(),
                        ingresoVencimiento.getText())) {
                    if (gestor.verificacionFormatoInteger(ingresoPrecio.getText(),
                            ingresoStock.getText())) {
                        return true;
                    } else {
                        throw new ProductoCargaDatosException(9);
                    }
                } else {
                    throw new ProductoCargaDatosException(8);
                }
            } else {
                throw new ProductoCargaDatosException(7);
            }
        } else {
            throw new ProductoCargaDatosException(7);
        }
    }

    private void btnGuardarIngresoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarIngresoMouseEntered
        // TODO add your handling code here:
        btnGuardarIngreso.setBackground(new Color(121, 215, 220));
        btnGuardarIngreso.setForeground(new Color(57, 136, 158));

    }//GEN-LAST:event_btnGuardarIngresoMouseEntered

    private void btnGuardarIngresoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarIngresoMouseExited
        // TODO add your handling code here:
        btnGuardarIngreso.setBackground(new Color(57, 136, 158));
        btnGuardarIngreso.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnGuardarIngresoMouseExited

    private void btnLimpiarIngreso1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarIngreso1MouseEntered
        // TODO add your handling code here:
        btnLimpiarIngreso1.setBackground(new Color(121, 215, 220));
        btnLimpiarIngreso1.setForeground(new Color(57, 136, 158));
    }//GEN-LAST:event_btnLimpiarIngreso1MouseEntered

    private void btnLimpiarIngreso1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarIngreso1MouseExited
        // TODO add your handling code here:
        btnLimpiarIngreso1.setBackground(new Color(57, 136, 158));
        btnLimpiarIngreso1.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnLimpiarIngreso1MouseExited

    private void btnLimpiarIngreso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarIngreso1ActionPerformed
        // TODO add your handling code here:
        ingresoMarca.setText("");
        ingresoNombre.setText("");
        ingresoElavoracion.setText("");
        ingresoVencimiento.setText("");
        ingresoStock.setText("");
        ingresoPrecio.setText("");
        selectorCategoria.setSelectedIndex(0);
        restablecerTextoIngreso();
        
    }//GEN-LAST:event_btnLimpiarIngreso1ActionPerformed
    //endregion
    private void btnGuardarIngresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarIngresoMouseClicked
        // TODO add your handling code here:
        try {
            if (verificacionFormato()) {
                dato.setIdProducto(gestor.crearIdProducto());
                dato.setMarca(ingresoMarca.getText());
                dato.setNombre(ingresoNombre.getText());
                dato.setFechaElavoracion(ingresoElavoracion.getText());
                dato.setFecheaDeVencimiento(ingresoVencimiento.getText());
                dato.setStock(Integer.parseInt(ingresoStock.getText()));
                dato.setPrecio(Integer.parseInt(ingresoPrecio.getText()));
                gestor.add(dato);
                JOptionPane.showMessageDialog(null, "Producto Ingresado Correctamente");
                restablecerTextoIngreso();
                dato = new Productos();
            }
        } catch (ProductoCargaDatosException e) {
            JOptionPane.showMessageDialog(null, e.escribirMensaje());
        }
    }//GEN-LAST:event_btnGuardarIngresoMouseClicked

    private void ingresoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoNombreActionPerformed

    private void ingresoNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresoNombreMouseClicked
        // TODO add your handling code here:
        if (ingresoMarca.getText().isEmpty()) {
            ingresoMarca.setForeground(new Color(153, 153, 153));
            ingresoMarca.setText("   Ingrese Marca del Producto");
        }
        if (ingresoNombre.getText().equals("   Ingrese Nombre del Producto")) {
            edicionLetraColortexto(ingresoNombre);
        }
        if (ingresoElavoracion.getText().isEmpty()) {
            ingresoElavoracion.setForeground(new Color(153, 153, 153));
            ingresoElavoracion.setText("   Ingrese Fecha de Elaboracion xx/xx/xxxx");
        }
        if (ingresoVencimiento.getText().isEmpty()) {
            ingresoVencimiento.setForeground(new Color(153, 153, 153));
            ingresoVencimiento.setText("   Ingrese Fecha de Vencimiento xx/xx/xxxx");
        }
        if (ingresoStock.getText().isEmpty()) {
            ingresoStock.setForeground(new Color(153, 153, 153));
            ingresoStock.setText("   Ingrese Stock Producto");

        }
        if (ingresoPrecio.getText().isEmpty()) {
            ingresoPrecio.setForeground(new Color(153, 153, 153));
            ingresoPrecio.setText("   Ingrese Precio Producto");

        }
    }//GEN-LAST:event_ingresoNombreMouseClicked

    private void ingresoMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresoMarcaMouseClicked
        // TODO add your handling code here:
        if (ingresoMarca.getText().equals("   Ingrese Marca del Producto")) {
            edicionLetraColortexto(ingresoMarca);
        }
        if (ingresoNombre.getText().isEmpty()) {
            ingresoNombre.setForeground(new Color(153, 153, 153));
            ingresoNombre.setText("   Ingrese Nombre del Producto");
        }
        if (ingresoElavoracion.getText().isEmpty()) {
            ingresoElavoracion.setForeground(new Color(153, 153, 153));
            ingresoElavoracion.setText("   Ingrese Fecha de Elaboracion xx/xx/xxxx");
        }
        if (ingresoVencimiento.getText().isEmpty()) {
            ingresoVencimiento.setForeground(new Color(153, 153, 153));
            ingresoVencimiento.setText("   Ingrese Fecha de Vencimiento xx/xx/xxxx");
        }
        if (ingresoStock.getText().isEmpty()) {
            ingresoStock.setForeground(new Color(153, 153, 153));
            ingresoStock.setText("   Ingrese Stock Producto");

        }
        if (ingresoPrecio.getText().isEmpty()) {
            ingresoPrecio.setForeground(new Color(153, 153, 153));
            ingresoPrecio.setText("   Ingrese Precio Producto");

        }
    }//GEN-LAST:event_ingresoMarcaMouseClicked

    private void ingresoElavoracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresoElavoracionMouseClicked
        // TODO add your handling code here:
        if (ingresoMarca.getText().isEmpty()) {
            ingresoMarca.setForeground(new Color(153, 153, 153));
            ingresoMarca.setText("   Ingrese Marca del Producto");
        }
        if (ingresoNombre.getText().isEmpty()) {
            ingresoNombre.setForeground(new Color(153, 153, 153));
            ingresoNombre.setText("   Ingrese Nombre del Producto");
        }
        if (ingresoElavoracion.getText().equals("   Ingrese Fecha de Elaboracion xx/xx/xxxx")) {
            edicionLetraColortexto(ingresoElavoracion);
        }
        if (ingresoVencimiento.getText().isEmpty()) {
            ingresoVencimiento.setForeground(new Color(153, 153, 153));
            ingresoVencimiento.setText("   Ingrese Fecha de Vencimiento xx/xx/xxxx");
        }
        if (ingresoStock.getText().isEmpty()) {
            ingresoStock.setForeground(new Color(153, 153, 153));
            ingresoStock.setText("   Ingrese Stock Producto");

        }
        if (ingresoPrecio.getText().isEmpty()) {
            ingresoPrecio.setForeground(new Color(153, 153, 153));
            ingresoPrecio.setText("   Ingrese Precio Producto");

        }
    }//GEN-LAST:event_ingresoElavoracionMouseClicked

    private void ingresoPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresoPrecioMouseClicked
        // TODO add your handling code here:
        if (ingresoMarca.getText().isEmpty()) {
            ingresoMarca.setForeground(new Color(153, 153, 153));
            ingresoMarca.setText("   Ingrese Marca del Producto");
        }
        if (ingresoNombre.getText().isEmpty()) {
            ingresoNombre.setForeground(new Color(153, 153, 153));
            ingresoNombre.setText("   Ingrese Nombre del Producto");
        }
        if (ingresoElavoracion.getText().isEmpty()) {
            ingresoElavoracion.setForeground(new Color(153, 153, 153));
            ingresoElavoracion.setText("   Ingrese Fecha de Elaboracion xx/xx/xxxx");
        }
        if (ingresoVencimiento.getText().isEmpty()) {
            ingresoVencimiento.setForeground(new Color(153, 153, 153));
            ingresoVencimiento.setText("   Ingrese Fecha de Vencimiento xx/xx/xxxx");
        }
        if (ingresoStock.getText().isEmpty()) {
            ingresoStock.setForeground(new Color(153, 153, 153));
            ingresoStock.setText("   Ingrese Stock Producto");
        }
        if (ingresoPrecio.getText().equals("   Ingrese Precio Producto")) {
            edicionLetraColortexto(ingresoPrecio);
        }
    }//GEN-LAST:event_ingresoPrecioMouseClicked

    private void ingresoStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresoStockMouseClicked
        // TODO add your handling code here:

        if (ingresoMarca.getText().isEmpty()) {
            ingresoMarca.setForeground(new Color(153, 153, 153));
            ingresoMarca.setText("   Ingrese Marca del Producto");
        }
        if (ingresoNombre.getText().isEmpty()) {
            ingresoNombre.setForeground(new Color(153, 153, 153));
            ingresoNombre.setText("   Ingrese Nombre del Producto");
        }
        if (ingresoElavoracion.getText().isEmpty()) {
            ingresoElavoracion.setForeground(new Color(153, 153, 153));
            ingresoElavoracion.setText("   Ingrese Fecha de Elaboracion xx/xx/xxxx");
        }
        if (ingresoVencimiento.getText().isEmpty()) {
            ingresoVencimiento.setForeground(new Color(153, 153, 153));
            ingresoVencimiento.setText("   Ingrese Fecha de Vencimiento xx/xx/xxxx");
        }
        if (ingresoStock.getText().equals("   Ingrese Stock Producto")) {
            edicionLetraColortexto(ingresoStock);

        }
        if (ingresoPrecio.getText().isEmpty()) {
            ingresoPrecio.setForeground(new Color(153, 153, 153));
            ingresoPrecio.setText("   Ingrese Precio Producto");

        }
    }//GEN-LAST:event_ingresoStockMouseClicked

    private void ingresoVencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoVencimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoVencimientoActionPerformed

    private void ingresoVencimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresoVencimientoMouseClicked
        // TODO add your handling code here:
        if (ingresoMarca.getText().isEmpty()) {
            ingresoMarca.setForeground(new Color(153, 153, 153));

            ingresoMarca.setText("   Ingrese Marca del Producto");
        }
        if (ingresoNombre.getText().isEmpty()) {
            ingresoNombre.setForeground(new Color(153, 153, 153));
            ingresoNombre.setText("   Ingrese Nombre del Producto");
        }
        if (ingresoElavoracion.getText().isEmpty()) {
            ingresoElavoracion.setForeground(new Color(153, 153, 153));
            ingresoElavoracion.setText("   Ingrese Fecha de Elaboracion xx/xx/xxxx");
        }
        if (ingresoVencimiento.getText().equals("   Ingrese Fecha de Vencimiento xx/xx/xxxx")) {
            edicionLetraColortexto(ingresoVencimiento);
        }
        if (ingresoStock.getText().isEmpty()) {
            ingresoStock.setForeground(new Color(153, 153, 153));
            ingresoStock.setText("   Ingrese Stock Producto");

        }
        if (ingresoPrecio.getText().isEmpty()) {
            ingresoPrecio.setForeground(new Color(153, 153, 153));
            ingresoPrecio.setText("   Ingrese Precio Producto");

        }
    }//GEN-LAST:event_ingresoVencimientoMouseClicked

    private void selectorCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorCategoriaActionPerformed
        // TODO add your handling code here:
        gestor.selecionarCategoriaProductos(dato, selectorCategoria.getSelectedIndex());
    }//GEN-LAST:event_selectorCategoriaActionPerformed

    private void ingresoPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoPrecioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanelCargaProducto;
    private javax.swing.JButton btnGuardarIngreso;
    private javax.swing.JButton btnLimpiarIngreso1;
    private javax.swing.JLabel iconoPanelCarga;
    private javax.swing.JTextField ingresoElavoracion;
    private javax.swing.JTextField ingresoMarca;
    private javax.swing.JTextField ingresoNombre;
    private javax.swing.JTextField ingresoPrecio;
    private javax.swing.JTextField ingresoStock;
    private javax.swing.JTextField ingresoVencimiento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> selectorCategoria;
    // End of variables declaration//GEN-END:variables

}
