/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.ventanas.vistas.panelesTabbledVistas;

import com.org.example.Exceptions.UsuarioCargaDatosException;
import com.org.example.Exceptions.UsuarioNoEncontradoException;
import com.org.example.clases.Cliente;
import com.org.example.service.GestionImpleCliente;

import javax.swing.*;
import javax.swing.plaf.synth.SynthOptionPaneUI;
import java.awt.*;
import java.util.ArrayList;

/**
 *
 * @author Agus-Notebook
 */
public class PanelEdicionUsuario extends javax.swing.JPanel {

    public GestionImpleCliente gestor = new GestionImpleCliente();
    public static Cliente dato = new Cliente();
    private static  Cliente  clienteSeleccionado;

    public PanelEdicionUsuario(Cliente cliente) {
        clienteSeleccionado = cliente;
        initComponents();
    }



    /**
     * Creates new form PanelEdicionUsuario
     */

    public PanelEdicionUsuario(){
        initComponents();
    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanelEdicionUsuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BotonCancelar = new javax.swing.JPanel();
        txtCancelar = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JPanel();
        txtAceptar = new javax.swing.JLabel();
        ingresoNombreCliente = new javax.swing.JTextField();
        ingresoApellidoUsuario = new javax.swing.JTextField();
        ingresoDniUsuario = new javax.swing.JTextField();
        ingresoDireccionUsuario = new javax.swing.JTextField();
        ingresoEmailUsuario = new javax.swing.JTextField();
        ingresoPasswordUsuario = new javax.swing.JTextField();
        ingresoTelefonoUsuario = new javax.swing.JTextField();
        BuscarPorId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        backgroundPanelEdicionUsuario.setBackground(new java.awt.Color(252, 237, 186));
        backgroundPanelEdicionUsuario.setMaximumSize(new java.awt.Dimension(800, 510));
        backgroundPanelEdicionUsuario.setMinimumSize(new java.awt.Dimension(800, 510));
        backgroundPanelEdicionUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3804730mini.png"))); // NOI18N
        backgroundPanelEdicionUsuario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, 89));

        jPanel1.setBackground(new java.awt.Color(252, 222, 81));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));

        BotonCancelar.setBackground(new java.awt.Color(255, 195, 98));
        BotonCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 171, 98), 3));
        BotonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonCancelarMouseExited(evt);
            }
        });

        txtCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCancelar.setForeground(new java.awt.Color(96, 183, 252));
        txtCancelar.setText("CANCELAR");

        javax.swing.GroupLayout BotonCancelarLayout = new javax.swing.GroupLayout(BotonCancelar);
        BotonCancelar.setLayout(BotonCancelarLayout);
        BotonCancelarLayout.setHorizontalGroup(
            BotonCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonCancelarLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(txtCancelar)
                .addGap(20, 20, 20))
        );
        BotonCancelarLayout.setVerticalGroup(
            BotonCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonCancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        botonAceptar.setBackground(new java.awt.Color(255, 195, 98));
        botonAceptar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 171, 49), 3));
        botonAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAceptarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAceptarMouseExited(evt);
            }
        });

        txtAceptar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAceptar.setForeground(new java.awt.Color(96, 183, 252));
        txtAceptar.setText("ACEPTAR");
        txtAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAceptarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAceptarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout botonAceptarLayout = new javax.swing.GroupLayout(botonAceptar);
        botonAceptar.setLayout(botonAceptarLayout);
        botonAceptarLayout.setHorizontalGroup(
            botonAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonAceptarLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(txtAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        botonAceptarLayout.setVerticalGroup(
            botonAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonAceptarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        ingresoNombreCliente.setBackground(new java.awt.Color(255, 235, 145));
        ingresoNombreCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ingresoNombreCliente.setForeground(new java.awt.Color(246, 171, 49));
        ingresoNombreCliente.setText("NOMBRE");
        ingresoNombreCliente.setBorder(null);
        ingresoNombreCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresoNombreClienteMouseClicked(evt);
            }
        });
        ingresoNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoNombreClienteActionPerformed(evt);
            }
        });

        ingresoApellidoUsuario.setBackground(new java.awt.Color(255, 235, 145));
        ingresoApellidoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ingresoApellidoUsuario.setForeground(new java.awt.Color(246, 171, 49));
        ingresoApellidoUsuario.setText("APELLIDO");
        ingresoApellidoUsuario.setBorder(null);
        ingresoApellidoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresoApellidoUsuarioMouseClicked(evt);
            }
        });
        ingresoApellidoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoApellidoUsuarioActionPerformed(evt);
            }
        });

        ingresoDniUsuario.setBackground(new java.awt.Color(255, 235, 145));
        ingresoDniUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ingresoDniUsuario.setForeground(new java.awt.Color(246, 171, 49));
        ingresoDniUsuario.setText("DNI");
        ingresoDniUsuario.setBorder(null);
        ingresoDniUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresoDniUsuarioMouseClicked(evt);
            }
        });
        ingresoDniUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoDniUsuarioActionPerformed(evt);
            }
        });

        ingresoDireccionUsuario.setBackground(new java.awt.Color(255, 235, 145));
        ingresoDireccionUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ingresoDireccionUsuario.setForeground(new java.awt.Color(246, 171, 49));
        ingresoDireccionUsuario.setText("DIRECCION");
        ingresoDireccionUsuario.setBorder(null);
        ingresoDireccionUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresoDireccionUsuarioMouseClicked(evt);
            }
        });
        ingresoDireccionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoDireccionUsuarioActionPerformed(evt);
            }
        });

        ingresoEmailUsuario.setBackground(new java.awt.Color(255, 235, 145));
        ingresoEmailUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ingresoEmailUsuario.setForeground(new java.awt.Color(246, 171, 49));
        ingresoEmailUsuario.setText("EMAIL");
        ingresoEmailUsuario.setBorder(null);
        ingresoEmailUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresoEmailUsuarioMouseClicked(evt);
            }
        });
        ingresoEmailUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoEmailUsuarioActionPerformed(evt);
            }
        });

        ingresoPasswordUsuario.setBackground(new java.awt.Color(255, 235, 145));
        ingresoPasswordUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ingresoPasswordUsuario.setForeground(new java.awt.Color(246, 171, 49));
        ingresoPasswordUsuario.setText("CONTRASEÑA");
        ingresoPasswordUsuario.setBorder(null);
        ingresoPasswordUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresoPasswordUsuarioMouseClicked(evt);
            }
        });
        ingresoPasswordUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoPasswordUsuarioActionPerformed(evt);
            }
        });

        ingresoTelefonoUsuario.setBackground(new java.awt.Color(255, 235, 145));
        ingresoTelefonoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ingresoTelefonoUsuario.setForeground(new java.awt.Color(246, 171, 49));
        ingresoTelefonoUsuario.setText("TELEFONO");
        ingresoTelefonoUsuario.setBorder(null);
        ingresoTelefonoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresoTelefonoUsuarioMouseClicked(evt);
            }
        });
        ingresoTelefonoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoTelefonoUsuarioActionPerformed(evt);
            }
        });

        BuscarPorId.setBackground(new java.awt.Color(255, 235, 145));
        BuscarPorId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BuscarPorId.setForeground(new java.awt.Color(246, 171, 49));
        BuscarPorId.setText("ID USUARIO");
        BuscarPorId.setBorder(null);
        BuscarPorId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarPorIdMouseClicked(evt);
            }
        });
        BuscarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPorIdActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 235, 145));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lupa.png"))); // NOI18N
        jButton1.setText("BUSCAR");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 171, 98), 3));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {

            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(BotonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BuscarPorId))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ingresoPasswordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ingresoNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ingresoApellidoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ingresoDniUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ingresoDireccionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ingresoEmailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ingresoTelefonoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarPorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(25, 25, 25)
                .addComponent(ingresoNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingresoApellidoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingresoDniUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingresoDireccionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingresoEmailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingresoPasswordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingresoTelefonoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        backgroundPanelEdicionUsuario.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 320, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanelEdicionUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanelEdicionUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void reestablecerTextoCargaUsuario(){
        ingresoNombreCliente.setText("NOMBRE");
        ingresoApellidoUsuario.setText("APELLIDO");
        ingresoDireccionUsuario.setText("DIRECCION");
        ingresoEmailUsuario.setText("EMAIL");
        ingresoTelefonoUsuario.setText("TELEFONO");
        ingresoPasswordUsuario.setText("CONTRASEÑA");
        ingresoDniUsuario.setText("DNI");
    }
    private boolean verificacionFormato() throws UsuarioCargaDatosException {
        if (gestor.verificacionIngresoBases(
                ingresoNombreCliente.getText(),
                ingresoApellidoUsuario.getText(),
                ingresoDireccionUsuario.getText(),
                ingresoEmailUsuario.getText(),
                ingresoTelefonoUsuario.getText(),
                ingresoPasswordUsuario.getText(),
                ingresoDniUsuario.getText())) {
            if (gestor.verificarIngresosVacios(
                    ingresoPasswordUsuario.getText(),
                    ingresoApellidoUsuario.getText(),
                    ingresoDireccionUsuario.getText(),
                    ingresoEmailUsuario.getText(),
                    ingresoTelefonoUsuario.getText(),
                    ingresoPasswordUsuario.getText(),
                    ingresoDniUsuario.getText())) {
                    return true;
                } else {
                    throw new UsuarioCargaDatosException(
                            8);
                }
            } else {
                throw new UsuarioCargaDatosException(
                        7);
            }

        }


    private void ingresoNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoNombreClienteActionPerformed

    private void ingresoApellidoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoApellidoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoApellidoUsuarioActionPerformed

    private void ingresoDniUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoDniUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoDniUsuarioActionPerformed

    private void ingresoDireccionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoDireccionUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoDireccionUsuarioActionPerformed

    private void ingresoEmailUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoEmailUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoEmailUsuarioActionPerformed

    private void ingresoPasswordUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoPasswordUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoPasswordUsuarioActionPerformed

    private void ingresoTelefonoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoTelefonoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoTelefonoUsuarioActionPerformed

    private void txtAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAceptarMouseClicked

        // TODO add your handling code here:
        try{
            if (clienteSeleccionado != null){
                verificacionFormato();
                clienteSeleccionado.setNombre(
                        ingresoNombreCliente.getText());
                clienteSeleccionado.setApellido(
                        ingresoApellidoUsuario.getText());
                clienteSeleccionado.setDireccion(
                        ingresoDireccionUsuario.getText());
                clienteSeleccionado.setDni(
                        ingresoDniUsuario.getText());
                clienteSeleccionado.setEmail(
                        ingresoEmailUsuario.getText());
                clienteSeleccionado.setTelefono(
                        ingresoTelefonoUsuario.getText());
                clienteSeleccionado.setContrasenia(
                        ingresoPasswordUsuario.getText());
                gestor.update(clienteSeleccionado);
                System.out.println("Llega");
                gestor.guardar();
                System.out.println("Guardo");
                //this.listaTabla.remove(cliente);
                reestablecerTextoCargaUsuario();
            }

        }catch (UsuarioCargaDatosException e){
            JOptionPane.showMessageDialog(null, e.getMessage()+e.escribirMensaje());
        }
    }//GEN-LAST:event_txtAceptarMouseClicked

    private void ingresoPasswordUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresoPasswordUsuarioMouseClicked
   // TODO add your handling code here:
   ingresoPasswordUsuario.setText("");

    }//GEN-LAST:event_ingresoPasswordUsuarioMouseClicked

    private void txtAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAceptarMouseEntered
        // TODO add your handling code here:
        txtAceptar.setForeground(new Color(139,202,255));
        botonAceptar.setBackground(new Color(255,235,145));
        botonAceptar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,195,98),3));


    }//GEN-LAST:event_txtAceptarMouseEntered

    private void botonAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarMouseEntered
        // TODO add your handling code here:
        txtAceptar.setForeground(new Color(139,202,255));
        botonAceptar.setBackground(new Color(255,235,145));
        botonAceptar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,195,98),3));

    }//GEN-LAST:event_botonAceptarMouseEntered

    private void BotonCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCancelarMouseEntered
        // TODO add your handling code here:
        txtCancelar.setForeground(new Color(139,202,255));
        BotonCancelar.setBackground(new Color(255,235,145));
        BotonCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,195,98),3));
    }//GEN-LAST:event_BotonCancelarMouseEntered

    private void BotonCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCancelarMouseExited
        // TODO add your handling code here:
        BotonCancelar.setBackground(new java.awt.Color(255, 195, 98));
        BotonCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 171, 98), 3));
    }//GEN-LAST:event_BotonCancelarMouseExited

    private void botonAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarMouseExited
        // TODO add your handling code here:
        botonAceptar.setBackground(new java.awt.Color(255, 195, 98));
        botonAceptar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 171, 49), 3));
    }//GEN-LAST:event_botonAceptarMouseExited

    private void botonAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarMouseClicked
        // TODO add your handling code here:

        try{

            if (clienteSeleccionado != null){
                verificacionFormato();
                clienteSeleccionado.setNombre(
                        ingresoNombreCliente.getText());
                clienteSeleccionado.setApellido(
                        ingresoApellidoUsuario.getText());
                clienteSeleccionado.setDireccion(
                        ingresoDireccionUsuario.getText());
                clienteSeleccionado.setDni(
                        ingresoDniUsuario.getText());
                clienteSeleccionado.setEmail(
                        ingresoEmailUsuario.getText());
                clienteSeleccionado.setTelefono(
                        ingresoTelefonoUsuario.getText());
                clienteSeleccionado.setContrasenia(
                        ingresoPasswordUsuario.getText());
                gestor.update(clienteSeleccionado);
                System.out.println("Llega");
                gestor.guardar();
                System.out.println("Guardo");
                //this.listaTabla.remove(cliente);
                reestablecerTextoCargaUsuario();
            }




       }catch (UsuarioCargaDatosException e){
            JOptionPane.showMessageDialog(null, e.getMessage()+e.escribirMensaje());
        }


        
        
    }//GEN-LAST:event_botonAceptarMouseClicked

    private void BotonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCancelarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_BotonCancelarMouseClicked

    private void BuscarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPorIdActionPerformed
        // TODO add your handling code here:
        BuscarPorId.setText("");
        
    }//GEN-LAST:event_BuscarPorIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String id =  BuscarPorId.getText();
            gestor.cargar();
            clienteSeleccionado = gestor.getById(id);
            if(clienteSeleccionado!= null) {
                ingresoNombreCliente.setText(
                        clienteSeleccionado.getNombre());
                ingresoApellidoUsuario.setText(
                        clienteSeleccionado.getApellido());
                ingresoDniUsuario.setText(
                        clienteSeleccionado.getDni());
                ingresoDireccionUsuario.setText(
                        clienteSeleccionado.getDireccion());
                ingresoEmailUsuario.setText(
                        clienteSeleccionado.getEmail());
                ingresoPasswordUsuario.setText(
                        "*********");
                ingresoTelefonoUsuario.setText(
                        clienteSeleccionado.getTelefono());
            }else
                System.out.println("NO HAY CLIENTE");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BuscarPorIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarPorIdMouseClicked
        // TODO add your handling code here:
        BuscarPorId.setText("");
    }//GEN-LAST:event_BuscarPorIdMouseClicked



    private void ingresoNombreClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresoNombreClienteMouseClicked
        // TODO add your handling code here:
        ingresoNombreCliente.setText("");
    }//GEN-LAST:event_ingresoNombreClienteMouseClicked

    private void ingresoApellidoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresoApellidoUsuarioMouseClicked
ingresoApellidoUsuario.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoApellidoUsuarioMouseClicked

    private void ingresoDniUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresoDniUsuarioMouseClicked
        // TODO add your handling code here:
        ingresoDniUsuario.setText("");
    }//GEN-LAST:event_ingresoDniUsuarioMouseClicked

    private void ingresoDireccionUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresoDireccionUsuarioMouseClicked
        // TODO add your handling code here:
        ingresoDireccionUsuario.setText("");
       
    }//GEN-LAST:event_ingresoDireccionUsuarioMouseClicked

    private void ingresoEmailUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresoEmailUsuarioMouseClicked
        // TODO add your handling code here:
        ingresoEmailUsuario.setText("");
    }//GEN-LAST:event_ingresoEmailUsuarioMouseClicked

    private void ingresoTelefonoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresoTelefonoUsuarioMouseClicked
        // TODO add your handling code here:
        ingresoTelefonoUsuario.setText("");
    }//GEN-LAST:event_ingresoTelefonoUsuarioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonCancelar;
    private javax.swing.JTextField BuscarPorId;
    private javax.swing.JPanel backgroundPanelEdicionUsuario;
    private javax.swing.JPanel botonAceptar;
    private javax.swing.JTextField ingresoApellidoUsuario;
    private javax.swing.JTextField ingresoDireccionUsuario;
    private javax.swing.JTextField ingresoDniUsuario;
    private javax.swing.JTextField ingresoEmailUsuario;
    private javax.swing.JTextField ingresoNombreCliente;
    private javax.swing.JTextField ingresoPasswordUsuario;
    private javax.swing.JTextField ingresoTelefonoUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtAceptar;
    private javax.swing.JLabel txtCancelar;
    // End of variables declaration//GEN-END:variables
}
