/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.ventanas.vistas.panelesTabbledVistas;

/**
 *
 * @author Agus-Notebook
 */
public class PanelCargaProducto extends javax.swing.JPanel {

    /**
     * Creates new form PanelCargaProducto
     */
    public PanelCargaProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanelCargaProducto = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(800, 510));
        setMinimumSize(new java.awt.Dimension(800, 510));
        setPreferredSize(new java.awt.Dimension(800, 510));

        backgroundPanelCargaProducto.setBackground(new java.awt.Color(255, 204, 204));
        backgroundPanelCargaProducto.setMaximumSize(new java.awt.Dimension(800, 510));
        backgroundPanelCargaProducto.setMinimumSize(new java.awt.Dimension(800, 510));

        javax.swing.GroupLayout backgroundPanelCargaProductoLayout = new javax.swing.GroupLayout(backgroundPanelCargaProducto);
        backgroundPanelCargaProducto.setLayout(backgroundPanelCargaProductoLayout);
        backgroundPanelCargaProductoLayout.setHorizontalGroup(
            backgroundPanelCargaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        backgroundPanelCargaProductoLayout.setVerticalGroup(
            backgroundPanelCargaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundPanelCargaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanelCargaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanelCargaProducto;
    // End of variables declaration//GEN-END:variables
}
