/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.ventanas.vistas.panelesTabbledVistas;

/**
 *
 * @author Agus-Notebook
 */
public class PanelEdicionUsuario extends javax.swing.JPanel {

    /**
     * Creates new form PanelEdicionUsuario
     */
    public PanelEdicionUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanelEdicionUsuario = new javax.swing.JPanel();

        backgroundPanelEdicionUsuario.setBackground(new java.awt.Color(255, 255, 204));
        backgroundPanelEdicionUsuario.setMaximumSize(new java.awt.Dimension(800, 510));
        backgroundPanelEdicionUsuario.setMinimumSize(new java.awt.Dimension(800, 510));

        javax.swing.GroupLayout backgroundPanelEdicionUsuarioLayout = new javax.swing.GroupLayout(backgroundPanelEdicionUsuario);
        backgroundPanelEdicionUsuario.setLayout(backgroundPanelEdicionUsuarioLayout);
        backgroundPanelEdicionUsuarioLayout.setHorizontalGroup(
            backgroundPanelEdicionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        backgroundPanelEdicionUsuarioLayout.setVerticalGroup(
            backgroundPanelEdicionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanelEdicionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanelEdicionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanelEdicionUsuario;
    // End of variables declaration//GEN-END:variables
}
