/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.org.example.ventanas;

import com.org.example.Exceptions.UsuarioNoEncontradoException;
import com.org.example.service.GestionImpleCliente;
import com.org.example.service.Utils;

import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Agus-Notebook
 */
public class Login extends javax.swing.JFrame {
    int mouseX;
    int mouseY;
   
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondoLogin = new javax.swing.JPanel();
        superposicionBackground = new javax.swing.JLabel();
        barraSuperior = new javax.swing.JPanel();
        botonExitVentana = new javax.swing.JPanel();
        exitTexto = new javax.swing.JLabel();
        PanelIngresoDatos = new javax.swing.JPanel();
        textoTitulo = new javax.swing.JLabel();
        textoEmail = new javax.swing.JLabel();
        ingresoEmail = new javax.swing.JTextField();
        separador1 = new javax.swing.JSeparator();
        textoContraseña = new javax.swing.JLabel();
        separador2 = new javax.swing.JSeparator();
        ingresoContrasenia = new javax.swing.JPasswordField();
        iconoLogin = new javax.swing.JLabel();
        botonIngreso = new javax.swing.JPanel();
        textoIngreso = new javax.swing.JLabel();
        derechosAutores = new javax.swing.JLabel();
        backgroundLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1066, 600));
        setMinimumSize(new java.awt.Dimension(1066, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        panelFondoLogin.setBackground(new java.awt.Color(255, 255, 255));
        panelFondoLogin.setMinimumSize(new java.awt.Dimension(800, 600));
        panelFondoLogin.setPreferredSize(new java.awt.Dimension(800, 600));
        panelFondoLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        superposicionBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/persona.png"))); // NOI18N
        panelFondoLogin.add(superposicionBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 410, 210));

        barraSuperior.setOpaque(false);
        barraSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraSuperiorMouseDragged(evt);
            }
        });
        barraSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraSuperiorMousePressed(evt);
            }
        });

        botonExitVentana.setBackground(new java.awt.Color(232, 246, 255));
        botonExitVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonExitVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonExitVentanaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonExitVentanaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonExitVentanaMouseExited(evt);
            }
        });

        exitTexto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        exitTexto.setForeground(new java.awt.Color(0, 0, 0));
        exitTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTexto.setText("X");

        javax.swing.GroupLayout botonExitVentanaLayout = new javax.swing.GroupLayout(botonExitVentana);
        botonExitVentana.setLayout(botonExitVentanaLayout);
        botonExitVentanaLayout.setHorizontalGroup(
            botonExitVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );
        botonExitVentanaLayout.setVerticalGroup(
            botonExitVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout barraSuperiorLayout = new javax.swing.GroupLayout(barraSuperior);
        barraSuperior.setLayout(barraSuperiorLayout);
        barraSuperiorLayout.setHorizontalGroup(
            barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraSuperiorLayout.createSequentialGroup()
                .addGap(0, 1001, Short.MAX_VALUE)
                .addComponent(botonExitVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barraSuperiorLayout.setVerticalGroup(
            barraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonExitVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelFondoLogin.add(barraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 40));

        PanelIngresoDatos.setBackground(new java.awt.Color(142, 233, 239));
        PanelIngresoDatos.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));

        textoTitulo.setBackground(new java.awt.Color(57, 136, 158));
        textoTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        textoTitulo.setForeground(new java.awt.Color(57, 136, 158));
        textoTitulo.setText("LOGIN");

        textoEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoEmail.setForeground(new java.awt.Color(57, 136, 158));
        textoEmail.setText("Email");

        ingresoEmail.setBackground(new java.awt.Color(142, 233, 239));
        ingresoEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ingresoEmail.setForeground(new java.awt.Color(153, 153, 153));
        ingresoEmail.setText("Ingrese Email del Usuario");
        ingresoEmail.setBorder(null);
        ingresoEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresoEmailMousePressed(evt);
            }
        });

        separador1.setAlignmentX(2.0F);
        separador1.setAlignmentY(2.0F);

        textoContraseña.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textoContraseña.setForeground(new java.awt.Color(57, 136, 158));
        textoContraseña.setText("Contraseña");

        ingresoContrasenia.setBackground(new java.awt.Color(142, 233, 239));
        ingresoContrasenia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ingresoContrasenia.setForeground(new java.awt.Color(153, 153, 153));
        ingresoContrasenia.setText("***************");
        ingresoContrasenia.setBorder(null);
        ingresoContrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresoContraseniaMousePressed(evt);
            }
        });

        iconoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrito-de-compras128.png"))); // NOI18N

        botonIngreso.setBackground(new java.awt.Color(57, 136, 158));

        textoIngreso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textoIngreso.setForeground(new java.awt.Color(255, 255, 255));
        textoIngreso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoIngreso.setText("ENTRAR");
        textoIngreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textoIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    Boolean emailIsValid = Utils.validEmail(ingresoEmail.getText());
                    Boolean passwordIsValid = Utils.validPassword(ingresoContrasenia.getText());
                    GestionImpleCliente gestionImpleCliente = new GestionImpleCliente();
                    if(!emailIsValid || !passwordIsValid || !gestionImpleCliente.VerificarDatosLogin(ingresoEmail.getText(),
                            String.valueOf(ingresoContrasenia.getPassword()))) {
                        JOptionPane.showMessageDialog(null, "Email o contraseña invalidos");
                        ingresoContrasenia.setText("");
                        ingresoEmail.setText("");
//                        Login.this.dispose();
                    }else{
                        Login.this.dispose();
                        MenuInicio menuInicio = new MenuInicio();
                        menuInicio.setVisible(true);

                    }
                } catch (UsuarioNoEncontradoException e) {
                    JOptionPane.showMessageDialog(null,e.getMessage()+e.escribirMensaje());
                }catch (Exception e ){
                    System.out.println(e.getMessage());
                }
            }



            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoIngresoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoIngresoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonIngresoLayout = new javax.swing.GroupLayout(botonIngreso);
        botonIngreso.setLayout(botonIngresoLayout);
        botonIngresoLayout.setHorizontalGroup(
            botonIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        botonIngresoLayout.setVerticalGroup(
            botonIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelIngresoDatosLayout = new javax.swing.GroupLayout(PanelIngresoDatos);
        PanelIngresoDatos.setLayout(PanelIngresoDatosLayout);
        PanelIngresoDatosLayout.setHorizontalGroup(
            PanelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIngresoDatosLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(textoTitulo)
                .addGap(137, 137, 137))
            .addGroup(PanelIngresoDatosLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(iconoLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelIngresoDatosLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(PanelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(separador2)
                        .addComponent(textoContraseña)
                        .addComponent(separador1)
                        .addComponent(textoEmail)
                        .addComponent(ingresoEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                        .addComponent(ingresoContrasenia)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelIngresoDatosLayout.setVerticalGroup(
            PanelIngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIngresoDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoTitulo)
                .addGap(0, 0, 0)
                .addComponent(iconoLogin)
                .addGap(4, 4, 4)
                .addComponent(textoEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingresoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ingresoContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        panelFondoLogin.add(PanelIngresoDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 380, 460));

        derechosAutores.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        derechosAutores.setForeground(new java.awt.Color(232, 246, 255));
        derechosAutores.setText("Inc Equipo Dinamita ");
        panelFondoLogin.add(derechosAutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 550, -1, 50));

        backgroundLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondoLoginAplicacion.png"))); // NOI18N
        panelFondoLogin.add(backgroundLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barraSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraSuperiorMousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_barraSuperiorMousePressed

    private void barraSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraSuperiorMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-mouseX,y-mouseY);
    }//GEN-LAST:event_barraSuperiorMouseDragged

    private void botonExitVentanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonExitVentanaMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonExitVentanaMouseClicked

    private void botonExitVentanaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonExitVentanaMouseEntered
        // TODO add your handling code here:
      botonExitVentana.setBackground(new Color(237,80,122));
      exitTexto.setForeground(new Color(232,246,255));
    }//GEN-LAST:event_botonExitVentanaMouseEntered

    private void botonExitVentanaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonExitVentanaMouseExited
        // TODO add your handling code here:
        botonExitVentana.setBackground(new Color(232,246,255));
        exitTexto.setForeground(Color.BLACK);
    }//GEN-LAST:event_botonExitVentanaMouseExited

    private void textoIngresoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoIngresoMouseEntered
        // TODO add your handling code here:
        botonIngreso.setBackground(new Color(81,204,210));
    }//GEN-LAST:event_textoIngresoMouseEntered

    private void textoIngresoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoIngresoMouseExited
        // TODO add your handling code here:
        botonIngreso.setBackground(new Color(57,136,158));
    }//GEN-LAST:event_textoIngresoMouseExited

    private void textoIngresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoIngresoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_textoIngresoMouseClicked

    private void ingresoEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresoEmailMousePressed
        // TODO add your handling code here:
        if(ingresoEmail.getText().equals("Ingrese Email del Usuario")){
            ingresoEmail.setText("");
            if(String.valueOf(ingresoContrasenia.getPassword()).isEmpty()){
                ingresoContrasenia.setText("***************");
                
            }
        }
    }//GEN-LAST:event_ingresoEmailMousePressed

    private void ingresoContraseniaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresoContraseniaMousePressed
        // TODO add your handling code here:
        if(String.valueOf(ingresoContrasenia.getPassword()).equals("***************")){
            ingresoContrasenia.setText("");
        }
        if(ingresoEmail.getText().isEmpty()){
            ingresoEmail.setText("Ingrese Email del Usuario");
        }
    }//GEN-LAST:event_ingresoContraseniaMousePressed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelIngresoDatos;
    private javax.swing.JLabel backgroundLogin;
    private javax.swing.JPanel barraSuperior;
    private javax.swing.JPanel botonExitVentana;
    private javax.swing.JPanel botonIngreso;
    private javax.swing.JLabel derechosAutores;
    private javax.swing.JLabel exitTexto;
    private javax.swing.JLabel iconoLogin;
    private javax.swing.JPasswordField ingresoContrasenia;
    private javax.swing.JTextField ingresoEmail;
    private javax.swing.JPanel panelFondoLogin;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JLabel superposicionBackground;
    private javax.swing.JLabel textoContraseña;
    private javax.swing.JLabel textoEmail;
    private javax.swing.JLabel textoIngreso;
    private javax.swing.JLabel textoTitulo;
    // End of variables declaration//GEN-END:variables
}
